config/routes.rb
Rails.application.routes.draw do
  root :to => "home#index",
    :protocol => (Rails.application.config.force_ssl ? "https://" : "http://"),
    :as => "root"

  get "/404" => "home#four_oh_four", :via => :all

  get "/rss" => "home#index", :format => "rss"
  get "/hottest" => "home#index", :format => "json"

  get "/page/:page" => "home#index"

  get "/newest" => "home#newest"
  get "/newest/page/:page" => "home#newest"
  get "/newest/:user" => "home#newest_by_user"
  get "/newest/:user/page/:page" => "home#newest_by_user"
  get "/recent" => "home#recent"
  get "/recent/page/:page" => "home#recent"
  get "/hidden" => "home#hidden"
  get "/hidden/page/:page" => "home#hidden"

  get "/saved" => "home#saved"
  get "/saved/page/:page" => "home#saved"
  get "/upvoted/stories" => "home#upvoted"
  get "/upvoted/stories/page/:page" => "home#upvoted"
  get "/upvoted/comments" => "comments#upvoted"
  get "/upvoted/comments/page/:page" => "comments#upvoted"
  get "/upvoted", to: redirect('/upvoted/stories')
  get "/upvoted/page/:page", to: redirect('/upvoted/stories/page/%{page}')

  get "/top" => "home#top"
  get "/top/page/:page" => "home#top"
  get "/top/:length" => "home#top"
  get "/top/:length/page/:page" => "home#top"

  get "/threads" => "comments#threads"
  get "/threads/:user" => "comments#threads", :as => "user_threads"

  get "/replies" => "replies#all"
  get "/replies/page/:page" => "replies#all"
  get "/replies/comments" => "replies#comments"
  get "/replies/comments/page/:page" => "replies#comments"
  get "/replies/stories" => "replies#stories"
  get "/replies/stories/page/:page" => "replies#stories"
  get "/replies/unread" => "replies#unread"
  get "/replies/unread/page/:page" => "replies#unread"

  get "/login" => "login#index"
  post "/login" => "login#login"
  post "/logout" => "login#logout"
  get "/login/2fa" => "login#twofa"
  post "/login/2fa_verify" => "login#twofa_verify", :as => "twofa_login"

  get "/signup" => "signup#index"
  post "/signup" => "signup#signup"
  get "/signup/invite" => "signup#invite"

  get "/login/forgot_password" => "login#forgot_password",
    :as => "forgot_password"
  post "/login/reset_password" => "login#reset_password",
    :as => "reset_password"
  match "/login/set_new_password" => "login#set_new_password",
    :as => "set_new_password", :via => [:get, :post]

  get "/t/:tag" => "home#tagged", :as => "tag"
  get "/t/:tag/page/:page" => "home#tagged"

  get "/search" => "search#index"
  get "/search/:q" => "search#index"

  resources :stories, except: [:index] do
    get '/stories/:short_id', to: redirect('/s/%{short_id}')
    post "upvote"
    post "downvote"
    post "unvote"
    post "undelete"
    post "hide"
    post "unhide"
    post "save"
    post "unsave"
    get "suggest"
    post "suggest", :action => "submit_suggestions"
  end
  post "/stories/fetch_url_attributes", :format => "json"
  post "/stories/preview" => "stories#preview"
  post "/stories/check_url_dupe" => "stories#check_url_dupe"

  resources :comments, except: [:new] do
    member do
      get "/comments/:id" => "comments#redirect_from_short_id"
      get "reply"
      post "upvote"
      post "downvote"
      post "unvote"

      post "delete"
      post "undelete"
      post "disown"
    end
  end
  get "/comments/page/:page" => "comments#index"
  get "/comments" => "comments#index"

  get "/messages/sent" => "messages#sent"
  get "/messages" => "messages#index"
  post "/messages/batch_delete" => "messages#batch_delete",
    :as => "batch_delete_messages"
  resources :messages do
    post "keep_as_new"
    post "mod_note"
  end

  get "/c/:id" => "comments#redirect_from_short_id"
  get "/c/:id.json" => "comments#show_short_id", :format => "json"

  # deprecated
  get "/s/:story_id/:title/comments/:id" => "comments#redirect_from_short_id"

  get "/s/:id/(:title)" => "stories#show"

  get "/u" => "users#tree"
  get "/u/:username" => "users#show", :as => "user"

  get "/avatars/:username_size.png" => "avatars#show"
  post "/avatars/expire" => "avatars#expire"

  post "/users/:username/ban" => "users#ban", :as => "user_ban"
  post "/users/:username/unban" => "users#unban", :as => "user_unban"
  post "/users/:username/disable_invitation" => "users#disable_invitation",
        :as => "user_disable_invite"
  post "/users/:username/enable_invitation" => "users#enable_invitation",
        :as => "user_enable_invite"

  get "/settings" => "settings#index"
  post "/settings" => "settings#update"
  post "/settings/delete_account" => "settings#delete_account",
    :as => "delete_account"
  get "/settings/2fa" => "settings#twofa", :as => "twofa"
  post "/settings/2fa_auth" => "settings#twofa_auth", :as => "twofa_auth"
  get "/settings/2fa_enroll" => "settings#twofa_enroll",
    :as => "twofa_enroll"
  get "/settings/2fa_verify" => "settings#twofa_verify",
    :as => "twofa_verify"
  post "/settings/2fa_update" => "settings#twofa_update",
    :as => "twofa_update"

  post "/settings/pushover_auth" => "settings#pushover_auth"
  get "/settings/pushover_callback" => "settings#pushover_callback"
  get "/settings/github_auth" => "settings#github_auth"
  get "/settings/github_callback" => "settings#github_callback"
  post "/settings/github_disconnect" => "settings#github_disconnect"
  get "/settings/twitter_auth" => "settings#twitter_auth"
  get "/settings/twitter_callback" => "settings#twitter_callback"
  post "/settings/twitter_disconnect" => "settings#twitter_disconnect"

  resources :keybase_proofs, only: [:new, :create, :destroy]
  get "/.well-known/keybase-proof-config" => "keybase_proofs#kbconfig", :as => "keybase_config"

  get "/filters" => "filters#index"
  post "/filters" => "filters#update"

  get "/tags" => "tags#index"
  get "/tags.json" => "tags#index", :format => "json"
  get "/tags/new" => "tags#new", :as => "new_tag"
  get "/tags/:id/edit" => "tags#edit", :as => "edit_tag"
  post "/tags" => "tags#create"
  post "/tags/:id" => "tags#update", :as => "update_tag"

  post "/invitations" => "invitations#create"
  get "/invitations" => "invitations#index"
  get "/invitations/request" => "invitations#build"
  post "/invitations/create_by_request" => "invitations#create_by_request",
    :as => "create_invitation_by_request"
  get "/invitations/confirm/:code" => "invitations#confirm_email"
  post "/invitations/send_for_request" => "invitations#send_for_request",
    :as => "send_invitation_for_request"
  get "/invitations/:invitation_code" => "signup#invited"
  post "/invitations/delete_request" => "invitations#delete_request",
    :as => "delete_invitation_request"

  get "/hats" => "hats#index"
  get "/hats/build_request" => "hats#build_request",
    :as => "request_hat"
  post "/hats/create_request" => "hats#create_request",
    :as => "create_hat_request"
  get "/hats/requests" => "hats#requests_index"
  post "/hats/approve_request/:id" => "hats#approve_request",
    :as => "approve_hat_request"
  post "/hats/reject_request/:id" => "hats#reject_request",
    :as => "reject_hat_request"

  get "/moderations" => "moderations#index"
  get "/moderations/page/:page" => "moderations#index"
  get "/moderators" => "users#tree", :moderators => true

  get "/mod" => "mod#index"
  get "/mod/flagged/:period"   => "mod#flagged",   :as => "mod_flagged"
  get "/mod/downvoted/:period" => "mod#downvoted", :as => "mod_downvoted"
  get "/mod/commenters/:period" => "mod#commenters", :as => "mod_commenters"
  get "/mod/notes(/:period)" => "mod_notes#index", :as => "mod_notes"
  post "/mod/notes" => "mod_notes#create"

  get "/privacy" => "home#privacy"
  get "/about" => "home#about"
  get "/chat" => "home#chat"

  post '/csp-violation-report' => 'csp#violation_report'
end

app/helpers/stories_helper.rb
module StoriesHelper
  def show_guidelines?
    if !@user
      return true
    end

    if @user.stories_submitted_count <= 5
      return true
    end

    if Moderation.joins(:story)
                 .where(
                   "stories.user_id = ? AND moderations.created_at > ?",
                   @user.id,
                   5.days.ago
                 ).exists?
      return true
    end

    false
  end

  def is_unread?(comment)
    if !@user || !@ribbon
      return false
    end

    (comment.created_at > @ribbon.updated_at) && (comment.user_id != @user.id)
  end
end

app/views/stories/_form.html.erb
<%= render :partial => "stories/form_errors", :locals => { :f => f, :story => f.object } %>

<div class="box">
  <% unless defined?(suggesting) %>
    <div class="boxline">
    <% if f.object.url_is_editable_by_user?(@user) %>
      <%= f.label :url, "URL:", :class => "required" %>
      <%= f.text_field :url, :autocomplete => "off" %>
      <%= button_tag "Fetch Title", :id => "story_fetch_title",
        :type => "button" %>
    <% elsif !f.object.new_record? && !f.object.url.blank? %>
      <%= f.label :url, "URL:", :class => "required" %>
      <div class="d">
      <a href="<%= f.object.url %>"><%= f.object.url %></a>
      </div>
    <% end %>
    </div>
  <% end %>

  <div class="boxline">
    <%= f.label :title, "Title:", :class => "required" %>
    <%= f.text_field :title, :maxlength => 100 %>
    <p class="actions title-reminder">
      Please remove extraneous components from titles such as the name of the site, blog, section, and author.
    </p>
  </div>

  <% if f.object.id && !defined?(suggesting) && f.object.suggested_title_times.any? %>
    <div class="boxline actions">
      Users have suggested setting this story's title to:
      <br>
      <% f.object.suggested_title_times.each do |st| %>
        <%= st.times %>: <%= st.title %><br>
      <% end %>
    </div>
  <% end %>

  <div class="boxline" style="margin-bottom: 2px;">
  <%= f.label :tags_a, "Tags:", :class => "required",
    :style => "line-height: 2.3em;" %>
  <%= f.select "tags_a", options_for_select(
    Tag.all_with_filtered_counts_for(@user).map{|t|
      html = "<strong>#{h(t.tag)}</strong> - #{h(t.description.to_s)}"

      if t.hotness_mod != 0
        html << " (hotness mod #{t.hotness_mod > 0 ? "+" : ""}#{t.hotness_mod})"
      end
      if t.filtered_count > 0
        html << " <em>#{t.filtered_count} user" <<
          (t.filtered_count == 1 ? "" : "s") << " filtering</em>"
      end

      [ "#{t.tag} - #{t.description}", t.tag, { "data-html" => raw(html) } ]},
    f.object.tags_a), {}, { :multiple => true } %>
  </div>

  <% if f.object.id && !defined?(suggesting) && f.object.suggested_tagging_times.any? %>
    <div class="boxline actions">
      Users have suggested setting this story's tags to:
      <br>
      <% f.object.suggested_tagging_times.includes(:tag).each do |st| %>
        <%= st.times %>: <%= tag_link(st.tag) %><br>
      <% end %>
    </div>
  <% end %>

  <% unless defined?(suggesting) %>
    <div class="boxline">
      <%= f.label :description, "Text:", :class => "required" %>
      <%= f.text_area :description, :rows => 15, :placeholder => "Optional when submitting a URL.
Not for summarizing the post or personal opinions.
See the guidelines below." %>
    </div>

    <div class="boxline actions markdown_help_toggler">
      <a href="#" id="story_guidelines_toggler">
        Story submission guidelines
      </a>
      <div id="story_guidelines" style="<%= show_guidelines?? "" : "display: none;" %>">
        <ul>

          <li><p>
          Do not editorialize story titles, but when the original story's
          title has no context or is unclear, please change it.  <strong>Please
          remove extraneous components from titles such as the name of the
          site, blog, section, and author.</strong>
          </p></li>

          <li><p>
          When the story being submitted is more than a year or so old,
          please add the year the story was written to the post title in
          parentheses.
          </p></li>

          <li><p>
          When submitting a URL, the text field is optional and should only
          be used when additional context or explanation of the URL is
          needed.  Commentary or opinion should be reserved for a comment,
          so that it can be voted on separately from the story.
          </p></li>

          <li><p>
          If no <a href="/tags">tags</a> clearly apply to the story you are submitting, chances
          are it does not belong here.  Do not overreach with tags if they
          are not the primary focus of the story.
          </p></li>

          <li><p>
          To be able to easily submit a page you're viewing in your browser
          to <%= Rails.application.name %>, drag this bookmarklet to your
          bookmark bar:
          [<a href="javascript:{window.open(%22<%= Rails.application.root_url
          %>stories/new?url=%22+encodeURIComponent(document.location)+<%
          %>%22&title=%22+encodeURIComponent(document.title));%20void(0);}<%
          %>">Submit to <%= Rails.application.name %></a>].
          You'll be taken to this page with the viewed page's URL and title.
          (It can't recognize and remove blog/author names for you, though.)
          </p></li>

        </ul>
      </div>
    </div>
  <% end %>
</div>
<% unless defined?(suggesting) %>
  <div class="box">
    <div class="boxline">
      <%= f.label :user_is_author, "Author:", :class => "required" %>
      <%= f.check_box :user_is_author %>
      <%= f.label :user_is_author,
        (f.object.id && f.object.user_id != @user.id ? "Submitter is" : "I am") +
        " the author of the story at this URL (or this text)",
        :class => "normal" %>
    </div>
    <div class="boxline">
      <%= f.label :user_is_following, "Follow:", :class => "required" %>
      <%= f.check_box :user_is_following %>
      <%= f.label :user_is_following,
        (f.object.id && f.object.user_id == @user.id ? 'Follow' : "Submitter is following") +
        " this story to receive replies via e-mail and Pushover",
        :class => "normal" %>
    </div>
  </div>

  <script>
    $(document).ready(function() {
      $("#story_fetch_title").click(function() {
        Lobsters.fetchURLTitle($(this), $("#story_url"), $("#story_title"));
        return false;
      });
    });
  </script>
<% end %>

app/views/stories/_form_errors.html.erb
<div>
  <div class="form_errors_header">
    <% if story.errors.count == 1 && story.already_posted_recently? %>
      <div class="flash-error">
        <h2>Error: This story was submitted <%= time_ago_in_words_label(story.most_recent_similar.created_at) %></h2>
      </div>
    <% elsif story.errors.any? && !story.already_posted_recently? %>
      <%= error_messages_for story %>
    <% elsif !story.errors.any? && story.public_similar_stories.any? %>
      <div class="flash-notice">
        <h2>Note: This story was already submitted <%= time_ago_in_words_label(story.most_recent_similar.created_at) %>, but may be submitted again.</h2>
        <p>
        If the content has changed or warrants new discussion, you may submit it again.
        </p>
      </div>

      <% if defined?(f) %>
        <%= f.hidden_field :seen_previous %>
      <% else %>
        <%= form_with model: story, local: true do |f| %>
          <%= f.hidden_field :seen_previous %>
        <% end %>
      <% end %>
    <% end %>

    <% if story.public_similar_stories.any? %>
      <p>Previous discussions for this story:</p>
      <%= render partial: "stories/similar", locals: { similar: story.similar_stories } %>
    <% end %>
  </div>
</div>

app/views/stories/_listdetail.html.erb
<%#
  The h-entry, u-report-of, u-url and h-card css classes are necessary
  for the webmentions support. http://microformats.org/wiki/h-entry
%>
<li id="story_<%= story.short_id %>" data-shortid="<%= story.short_id %>"
class="story <%= story.vote && story.vote[:vote] == 1 ? "upvoted" : "" %>
<%= story.vote && story.vote[:vote] == -1 ? "downvoted" : "" %>
<%= story.score <= -1 ? "negative_1" : "" %>
<%= story.score <= -3 ? "negative_3" : "" %>
<%= story.score <= -5 ? "negative_5" : "" %>
<%= story.is_hidden_by_cur_user ? "hidden" : "" %>
<%= story.is_saved_by_cur_user ? "saved" : "" %>
<%= story.is_expired? ? "expired" : "" %>">
<div class="story_liner h-entry">
  <div class="voters">
    <% if @user %>
      <a class="upvoter" title="Add upvote"></a>
    <% else %>
      <%= link_to "", login_path, :class => "upvoter" %>
    <% end %>
    <div class="score"><%= story.show_score_to_user?(@user) ? story.score : '~' %></div>
  </div>
  <div class="details">
    <span class="link h-cite u-repost-of">
      <% if story.can_be_seen_by_user?(@user) %>
        <a class="u-url" href="<%= story.url_or_comments_path %>"><%=
          break_long_words(story.title) %></a>
      <% end %>
      <% if story.is_gone? %>
        [Story removed by <%= story.is_moderated? ? "moderator" :
          "original submitter" %>]
      <% end %>
    </span>
    <% if story.markeddown_description.present? %>
      <a class="description_present" title="<%= truncate(story.description,
        :length => 500) %>" href="<%= story.comments_path %>">&#x2636;</a>
    <% end %>
    <% if story.can_be_seen_by_user?(@user) %>
      <span class="tags">
        <% story.tags.each do |tag| %>
          <%= tag_link(tag) %>
        <% end %>
      </span>
      <% if story.domain.present? %>
        <a class="domain" href="<%= story.domain_search_url %>"><%=
          break_long_words(story.domain) %></a>
      <% end %>

      <% if defined?(single_story) && single_story %>
        <% story.merged_stories.not_deleted.includes(:user, :tags).each do |ms| %>
          <br>
          <span class="merge"></span>
          <span class="link">
            <a href="<%= ms.url_or_comments_path %>"><%=
              break_long_words(ms.title) %></a>
          </span>
          <span class="tags">
            <% ms.tags.each do |tag| %>
              <a href="<%= tag_path(tag) %>"
                class="<%= tag.css_class %>"
                title="<%= tag.description %>"><%= tag.tag %></a>
            <% end %>
          </span>
          <% if ms.domain.present? %>
            <a class="domain" href="<%= ms.domain_search_url %>"><%=
              break_long_words(ms.domain) %></a>
          <% end %>
          <span class="byline">
            <% if (@user && @user.show_avatars?) || !@user %>
              <a href="/u/<%= ms.user.username %>"><%=
                avatar_img(ms.user, 16) %></a>
            <% end %>
            <% if story.user_is_author? %>
              authored by
            <% else %>
              via
            <% end %>
            <a href="/u/<%= ms.user.username %>" class="u-author h-card <%=
              ms.html_class_for_user %>"><%= ms.user.username %></a>

            <%= time_ago_in_words_label(ms.created_at) %>
            <% if ms.is_editable_by_user?(@user) %>
              |
              <a href="<%= edit_story_path(ms.short_id) %>">edit</a>
            <% end %>
          </span>
        <% end %>
      <% end %>
    <% end %>

    <% if !(defined?(single_story) && single_story) && @user &&
    @user.show_story_previews? %>
      <% if (sc = story.description_or_story_cache(500)).present? %>
        <div class="story_content">
          <%= break_long_words(sc) %>
        </div>
      <% end %>
    <% end %>

    <div class="byline">
      <% if (@user && @user.show_avatars?) || !@user %>
        <a href="/u/<%= story.user.username %>"><%=
          avatar_img(story.user, 16) %></a>
      <% end %>
      <% if story.previewing %>
        <% if story.user_is_author? %>
          authored by
        <% else %>
          via
        <% end %>
        <a class="u-author h-card <%= story.html_class_for_user %>"><%=
          story.user.username %></a>
        just now
      <% else %>
        <% if story.user_is_author? %>
          authored by
        <% else %>
          via
        <% end %>
        <a href="/u/<%= story.user.username %>" class="u-author h-card <%=
          story.html_class_for_user %>"><%= story.user.username %></a>

        <%= time_ago_in_words_label(story.created_at) %>

        <% if story.is_editable_by_user?(@user) %>
          |
          <a href="<%= edit_story_path(story.short_id) %>" class="<%=
            story.has_suggestions? ? "story_has_suggestions" : "" %>">edit</a>
        <% end %>
        <% if story.can_have_suggestions_from_user?(@user) %>
          | <%= link_to "suggest", story_suggest_path(story.short_id),
            :class => "suggester" %>
        <% end %>
        <% if !story.is_gone? && @user %>
          <% if @user && story.vote && story.vote[:vote] == -1 %>
            | <a class="flagger">unflag (<%=
              Vote::STORY_REASONS[story.vote[:reason]].to_s.downcase %>)</a>
          <% elsif @user && @user.can_downvote?(story) %>
            | <a class="flagger">flag</a>
          <% end %>
          <% if story.is_hidden_by_cur_user %>
            | <%= link_to "unhide", story_unhide_path(story.short_id),
              :class => "hider" %>
          <% else %>
            | <%= link_to "hide", story_hide_path(story.short_id),
              :class => "hider" %>
          <% end %>
          <% if defined?(single_story) && single_story && story.hider_count > 0 %>
            (hidden by <%= pluralize(story.hider_count, "user") %>)
          <% end %>
          <% if story.is_saved_by_cur_user %>
            | <%= link_to "unsave", story_unsave_path(story.short_id),
              :class => "saver" %>
          <% else %>
            | <%= link_to "save", story_save_path(story.short_id),
              :class => "saver" %>
          <% end %>
        <% end %>
        <% if story.url.present? %>
          |
          <a href="<%= story.archive_url %>" rel="nofollow"
            target="_blank">cached</a>
        <% end %>
        <% if !story.is_gone? %>
          <span class="comments_label">
            |
            <a href="<%= story.comments_path %>">
            <% if story.comments_count == 0 %>
              no comments</a>
            <% else %>
              <%= story.comments_count %> <%= 'comment'.pluralize(story.comments_count) %></a>
            <% end %>
          </span>
        <% end %>

        <% if defined?(single_story) && single_story &&
        ((story.downvotes > 0 && @user && @user.is_moderator?) ||
        (story.downvotes >= 3 || story.score <= 0)) %>
          | <%= story.vote_summary_for(@user).downcase %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<a href="<%= story.comments_path %>" class="mobile_comments <%= story.comments_count == 0 ? "zero" : "" %>" style="display: none;">
  <span><%= story.comments_count %></span>
</a>
</li>

app/views/stories/_similar.html.erb
<ol>
  <% similar.each do |story| %>
    <li>
      <a href="<%= story.url %>" target="_blank"><%= story.title %></a>
      <%= story.user_is_author? ? "authored by" : "via" %>
      <a href="/u/<%= story.user.username %>" class="<%= story.html_class_for_user %>"><%= story.user.username %></a>
      <%= time_ago_in_words_label(story.created_at) %>
      <span>
        |
        <%= story.show_score_to_user?(@user) ? "#{story.score} point".pluralize(story.score) : '~' %>
      </span>
      <span class="comments_label">
        |
        <a href="<%= story.comments_path %>">
          <% if story.comments_count == 0 %>
            no comments</a>
          <% else %>
            <%= story.comments_count %> <%= 'comment'.pluralize(story.comments_count) %></a>
          <% end %>
      </span>
    </li>
  <% end %>
</ol>

app/views/stories/edit.html.erb
<div class="box" id="story_box">
  <div class="legend">
    Edit Story
  </div>

  <%= form_with model: @story, url: story_path(@story.short_id), method: :put, id: 'edit_story', local: true do |f| %>
    <%= render :partial => "stories/form", :locals => { :story => @story,
      :f => f } %>

    <% if @user.is_moderator? %>
      <br />
      <div class="box">
        <div class="boxline">
          <%= f.label :merge_story_short_id, "Merge Into:",
            :class => "required" %>
          <%= f.text_field :merge_story_short_id, :autocomplete => "off",
            :placeholder => "Short id of story into which this story " <<
            "be merged" %>
        </div>
        <div class="boxline">
          <%= f.label :unavailable_at, "Unavailable:",
            :class => "required" %>
          <%= f.check_box :is_unavailable %>
          <%= f.label :unavailable_at, "Source URL is unavailable, " <<
            "enable display of cached text", :class => "normal" %>
        </div>
        <% if @story.user_id != @user.id %>
          <div class="boxline">
            <%= f.label :moderation_reason, "Mod Reason:", :class => "required" %>
            <%= f.text_field :moderation_reason %>
          </div>
        <% end %>
      </div>
    <% end %>

    <p></p>

    <div class="box">
      <div class="boxline actions markdown_help_toggler">
        <div class="markdown_help_label">
          Markdown formatting available
        </div>

        <%= f.submit "Save" %>

        <% if @story.is_gone? && @story.is_undeletable_by_user?(@user) %>
          &nbsp; | &nbsp;
          <%= link_to "Undelete", story_undelete_path(@story.short_id),
            :method => :post, :data => {
            :confirm => "Are you sure you want to undelete this story?" },
            :class => "button" %>
        <% elsif !@story.is_gone? %>
          &nbsp; | &nbsp;
          <% if @story.user_id != @user.id && @user.is_moderator? %>
            <%= link_to "Delete", story_path(@story.short_id),
              :method => :delete, :class => "button mod_story_link deletion" %>
          <% else %>
            <%= link_to "Delete", story_path(@story.short_id),
              :method => :delete, :data => {
              :confirm => "Are you sure you want to delete this story?" },
              :class => "button" %>
          <% end %>
        <% end %>

        <div style="clear: both;"></div>

        <%= render :partial => "global/markdownhelp",
          :locals => { allow_images: @story.can_have_images? } %>
      </div>
    </div>
  <% end %>
</div>

app/views/stories/new.html.erb
<div class="box" id="story_box">
  <div class="legend">
    Submit a Story
  </div>

  <div id="story_holder">
    <%= form_with model: @story, local: true do |f| %>
      <%= render :partial => "stories/form", :locals => { :story => @story, :f => f } %>

      <p></p>

      <div class="box">
        <div class="boxline actions markdown_help_toggler">
          <div class="markdown_help_label">
            Markdown formatting available
          </div>

          <%= f.submit "Submit" %>

          &nbsp;
          <button type="button" class="story-preview">Preview</button>

          <div style="clear: both;"></div>

          <%= render :partial => "global/markdownhelp",
            :locals => { allow_images: @story.can_have_images? } %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div id="story_preview">
  <% if @story.previewing && @story.valid? %>
    <%= render :template => "stories/show" %>
  <% end %>
</div>

<script>
  $(document).ready(function() {
    <% if !@story.previewing %>
      $("#story_url").focus();
    <% end %>
  });
</script>

app/views/stories/suggest.html.erb
<div class="box" id="story_box">
  <div class="legend">
    Suggest Story Changes
  </div>

  <%= form_with model: @story, url: story_suggest_path(@story.short_id), method: :post, html: { id: 'edit_story' }, local: true do |f| %>
    <%= render :partial => "stories/form", :locals => { :story => @story,
      :f => f, :suggesting => true } %>

    <p></p>

    <div class="box">
      <div class="boxline actions">
        <%= f.submit "Suggest Changes" %>
        &nbsp;or <a href="<%= story_path(@story.short_id) %>">cancel</a>
      </div>
    </div>
  <% end %>
</div>